# Generated by Django 3.2.11 on 2023-02-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_title', models.CharField(max_length=120, verbose_name='Subject')),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('db_sender', models.CharField(blank=True, max_length=120, verbose_name='Sender')),
                ('db_reciever', models.CharField(blank=True, max_length=120, verbose_name='Receiver')),
                ('db_body', models.TextField(verbose_name='Message Body')),
            ],
        ),
    ]
