# Generated by Django 3.2.11 on 2023-02-02 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('leader', models.CharField(max_length=120, verbose_name='Leader')),
                ('orders', models.TextField(blank=True)),
                ('members', models.ManyToManyField(blank=True, to='character.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('leader', models.CharField(max_length=120, verbose_name='Leader')),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(max_length=20)),
                ('radio_a', models.CharField(max_length=10)),
                ('radio_b', models.CharField(max_length=10)),
                ('motd', models.TextField(blank=True)),
                ('members', models.ManyToManyField(blank=True, to='character.Character')),
                ('squads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.squad')),
            ],
        ),
    ]
