# Generated by Django 3.2.11 on 2023-02-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergroup',
            name='db_twoic',
            field=models.CharField(default=1, max_length=120, verbose_name='Secondary Leader'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playergroup',
            name='db_radio_a',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Radio A'),
        ),
        migrations.AlterField(
            model_name='playergroup',
            name='db_radio_b',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Radio B'),
        ),
    ]
