# Generated by Django 3.2.11 on 2023-02-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '__first__'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='PlayerGroup',
        ),
    ]
