# Generated by Django 3.2.11 on 2023-02-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_group_playergroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergroup',
            old_name='color',
            new_name='db_color',
        ),
        migrations.RenameField(
            model_name='playergroup',
            old_name='description',
            new_name='db_description',
        ),
        migrations.RenameField(
            model_name='playergroup',
            old_name='leader',
            new_name='db_leader',
        ),
        migrations.RenameField(
            model_name='playergroup',
            old_name='members',
            new_name='db_members',
        ),
        migrations.RenameField(
            model_name='playergroup',
            old_name='motd',
            new_name='db_motd',
        ),
        migrations.RenameField(
            model_name='playergroup',
            old_name='name',
            new_name='db_name',
        ),
        migrations.RenameField(
            model_name='playergroup',
            old_name='radio_a',
            new_name='db_radio_a',
        ),
        migrations.RenameField(
            model_name='playergroup',
            old_name='radio_b',
            new_name='db_radio_b',
        ),
        migrations.RenameField(
            model_name='playergroup',
            old_name='squads',
            new_name='db_squads',
        ),
        migrations.RenameField(
            model_name='squad',
            old_name='leader',
            new_name='db_leader',
        ),
        migrations.RenameField(
            model_name='squad',
            old_name='members',
            new_name='db_members',
        ),
        migrations.RenameField(
            model_name='squad',
            old_name='name',
            new_name='db_name',
        ),
        migrations.RenameField(
            model_name='squad',
            old_name='orders',
            new_name='db_orders',
        ),
        migrations.AddField(
            model_name='playergroup',
            name='db_key',
            field=models.CharField(db_index=True, default=0, max_length=80),
        ),
        migrations.AddField(
            model_name='squad',
            name='db_key',
            field=models.CharField(db_index=True, default=0, max_length=100),
        ),
    ]
