# Generated by Django 3.2.11 on 2023-02-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_character_defaultcharacter_defaultexit_defaultobject_defaultroom_mobject_object'),
        ('groups', '0005_auto_20230203_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergroup',
            name='db_members',
            field=models.ManyToManyField(blank=True, to='objects.ObjectDB'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='db_members',
            field=models.ManyToManyField(blank=True, to='objects.ObjectDB'),
        ),
    ]
