# Generated by Django 3.2.11 on 2023-02-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20230203_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergroup',
            name='db_key',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='db_key',
        ),
        migrations.AlterField(
            model_name='playergroup',
            name='db_color',
            field=models.CharField(max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='playergroup',
            name='db_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='playergroup',
            name='db_motd',
            field=models.TextField(blank=True, verbose_name='Message of the Day'),
        ),
        migrations.AlterField(
            model_name='playergroup',
            name='db_radio_a',
            field=models.CharField(max_length=10, verbose_name='Radio A'),
        ),
        migrations.AlterField(
            model_name='playergroup',
            name='db_radio_b',
            field=models.CharField(max_length=10, verbose_name='Radio B'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='db_orders',
            field=models.TextField(blank=True, verbose_name='Orders'),
        ),
    ]
