# Generated by Django 3.2.11 on 2023-02-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20230203_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='db_name',
            field=models.CharField(max_length=100, verbose_name='Squad Name'),
        ),
    ]
