# Generated by Django 3.2.11 on 2023-02-06 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=120, verbose_name='Board Name')),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_title', models.CharField(max_length=120, verbose_name='Board Name')),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('posted_by', models.CharField(max_length=120, verbose_name='Author')),
                ('body_text', models.TextField(verbose_name='Post')),
                ('db_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.bulletinboard')),
            ],
        ),
    ]
