# Generated by Django 3.2.11 on 2023-03-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_bulletinboard_db_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpost',
            name='db_title',
            field=models.CharField(max_length=120, verbose_name='Post Title'),
        ),
    ]
