# Generated by Django 3.2.11 on 2023-02-06 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeraccount',
            name='db_date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playeraccount',
            name='db_name',
            field=models.CharField(default=1, max_length=120, verbose_name='Nickname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roster',
            name='db_date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roster',
            name='db_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
