# Generated by Django 3.2.11 on 2023-02-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_auto_20230206_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='db_name',
            field=models.CharField(default=0, max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
