# Generated by Django 3.2.11 on 2023-02-05 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_title', models.CharField(max_length=200, verbose_name='Name')),
                ('db_text', models.TextField(blank=True, verbose_name='File')),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('db_author', models.CharField(max_length=200, verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_key', models.CharField(max_length=200, unique=True, verbose_name='Keyword')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_text', models.TextField(blank=True, verbose_name='Response')),
                ('db_submitter', models.CharField(max_length=120, verbose_name='Submitter')),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=200, verbose_name='Name')),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('db_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_title', models.CharField(max_length=200, verbose_name='Title')),
                ('db_submitter', models.CharField(max_length=120, verbose_name='Submitter')),
                ('db_message_body', models.TextField(verbose_name='Message Body')),
                ('db_assigned_to', models.CharField(blank=True, max_length=120, verbose_name='Assigned To')),
                ('db_copied_to', models.TextField(blank=True, verbose_name='Copied To')),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('type', models.IntegerField(choices=[(1, 'General'), (2, 'Bugfix'), (3, 'Character'), (4, 'News'), (5, 'Build'), (6, 'Auto'), (7, 'Research')])),
                ('db_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.requestresponse')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='db_keywords',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.keyword'),
        ),
    ]
