# Generated by Django 3.2.11 on 2023-02-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_title', models.CharField(max_length=200, verbose_name='Title')),
                ('db_submitter', models.CharField(max_length=120, verbose_name='Submitter')),
                ('db_message_body', models.TextField(verbose_name='Message Body')),
                ('db_assigned_to', models.CharField(max_length=120, verbose_name='Assigned To')),
                ('db_copied_to', models.TextField(verbose_name='Copied To')),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('type', models.IntegerField(choices=[(1, 'General'), (2, 'Bugfix'), (3, 'Character'), (4, 'News'), (5, 'Build'), (6, 'Auto'), (7, 'Research')])),
            ],
        ),
    ]
