# Generated by Django 3.2.11 on 2023-02-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='id',
        ),
        migrations.AddField(
            model_name='request',
            name='db_key',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='db_assigned_to',
            field=models.CharField(blank=True, max_length=120, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='request',
            name='db_copied_to',
            field=models.TextField(blank=True, verbose_name='Copied To'),
        ),
    ]
