# Generated by Django 3.2.11 on 2023-02-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='up_to_date',
            field=models.BooleanField(default=True, verbose_name='Up to date?'),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.IntegerField(choices=[(1, 'General'), (2, 'Bugfix'), (3, 'Character'), (5, 'Build'), (6, 'Auto'), (4, 'ICNews'), (7, 'Research'), (8, 'Activity'), (9, 'HelpFile')]),
        ),
    ]
