# Generated by Django 3.2.11 on 2023-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20230210_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='db_is_open',
            field=models.BooleanField(default=True, verbose_name='Open'),
        ),
    ]
