# Generated by Django 3.2.11 on 2023-02-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20230203_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='db_key',
        ),
        migrations.AddField(
            model_name='request',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
