# Generated by Django 3.2.11 on 2023-02-04 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20230203_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_title', models.CharField(max_length=200, verbose_name='Name')),
                ('db_text', models.TextField(blank=True, verbose_name='File')),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('db_author', models.CharField(max_length=200, verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_key', models.CharField(max_length=200, verbose_name='Keyword')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_text', models.TextField(blank=True, verbose_name='Response')),
                ('db_submitter', models.CharField(max_length=120, verbose_name='Submitter')),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=200, verbose_name='Name')),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('db_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='file',
            name='db_keywords',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.keyword'),
        ),
        migrations.AddField(
            model_name='request',
            name='db_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.requestresponse'),
        ),
    ]
