# Generated by Django 3.2.11 on 2023-03-02 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_auto_20230301_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='db_date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='db_keywords',
            field=models.ManyToManyField(to='requests.Keyword'),
        ),
    ]
