# Generated by Django 3.2.11 on 2023-03-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_auto_20230301_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='db_date_created',
        ),
        migrations.RemoveField(
            model_name='file',
            name='db_keywords',
        ),
        migrations.AddField(
            model_name='file',
            name='db_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
    ]
