# Generated by Django 3.2.11 on 2023-03-11 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Capabilities',
            new_name='Capability',
        ),
    ]
