# Generated by Django 3.2.11 on 2023-03-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armor', '0002_rename_capabilities_capability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armormode',
            name='db_capabilities',
            field=models.ManyToManyField(blank=True, to='armor.Capability'),
        ),
    ]
