# Generated by Django 3.2.11 on 2023-03-11 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0001_initial'),
        ('armor', '0004_auto_20230311_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='armormode',
            name='db_primary',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_weapon', to='combat.weapon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armormode',
            name='db_secondary',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_weapon', to='combat.weapon'),
            preserve_default=False,
        ),
    ]
